### PR TITLE
Add sign-up button to login page.

### PR DESCRIPTION
**Pull request by JasonHoku**

### CODE REVIEW

**Comment by JasonHoku** [comment]
I ran ```python3 black {{cookiecutter.project_slug}}/backend```

But I am still getting failed black formatting. I've never worked with this before, but do want to help produce this app.

I have looked at several docs but do not know what I am missing.

**Comment by Buuntu** [comment]
I'm confused by this, it looks like it adds another Login Button that does the same thing?  I also would not add Routes directly to anything outside of Routes.  Use `history.push` for that.

The Black stuff is fine, that's an issue from before this PR.

**Comment by JasonHoku** [comment]
> I'm confused by this, it looks like it adds another Login Button that does the same thing? I also would not add Routes directly to anything outside of Routes. Use `history.push` for that.
> 
> The Black stuff is fine, that's an issue from before this PR.

Ah. Okay, I was testing the PR functions and got discouraged with the Black formatting check fail, I will tidy this up soon and correct the second button to read Sign-Up and history.push to the Sign Up page, knowing that I am not at fault for the formatting issues. Thank you. 🌞

**Comment by JasonHoku** [comment]
Okay! The sign up button is working perfectly using useHistory.

I've also added to the .gitignore to not add node_modules and the package-lock to the git repo in this PR.

**Pull request merged**
